[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.23"
evm_version = "cancun"
optimizer = true
optimizer_runs = 1000000
via_ir = true
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@account-abstraction/=lib/account-abstraction/contracts/",
    "forge-std/=lib/forge-std/src/",
    "@erc7579/=lib/erc7579-implementation/src/",
    "solady/=lib/solady/src/"
]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
base = "${BASE_RPC_URL}"
base-sepolia = "${BASE_SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.etherscan.io/api" }
base = { key = "${ETHERSCAN_API_KEY}", url = "https://api.basescan.org/api" }
base-sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

